source 'https://github.com/CocoaPods/Specs.git'

platform :ios, ’9.0‘

use_frameworks!
target “swiftText” do

pod 'SnapKit'
pod 'RxSwift'
pod 'RxCocoa'
pod 'Then'
pod 'ReactorKit'
pod 'RxDataSources'    
pod 'Moya/RxSwift'
pod 'MoyaSugar'
pod 'LLCycleScrollView'
pod 'RxViewController'
pod 'ReusableKit/RxSwift'
pod 'SDWebImage'
pod 'URLNavigator'
pod 'HandyJSON'
end



